markdown: rdiscount
permalink: /posts/:title.html
rdiscount:
  extensions: [smart]

gems:
  - jekyll-sitemap

name: Hearken Me
url: hearken.me
description: Please hearken me.
twitter: noah_zh
excerpt_separator: <!--more-->
